services:
  nuxt-container:
    build: .
    ports:
      - "2408:2408"
    command: ["pm2-runtime", "start", "ecosystem.config.cjs"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

